# Generated by Django 2.1.4 on 2018-12-30 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 15, 24, 34, 896194, tzinfo=utc)),
        ),
    ]
